### PR TITLE
Add preserve_null flag

### PR DESCRIPTION
**Pull request by dudicoco**
Added a new `preserve_null` flag which preserves null values:
```
foo: null
```

As described here:
https://stackoverflow.com/questions/57172997/yaml-dumper-outputs-blank-instead-of-null-from-none-value-how-to-make-it-output

### CODE REVIEW

**Comment by dudicoco** [comment]
@jumanjiman can you please approve?

**Comment by archoversight** [comment]
@dudicoco I'm still waiting on word on my merge request :/

**Comment by dudicoco** [comment]
@jumanjiman ?

**Comment by jumanjiman** [comment]
I'd love to merge this.
can you make it so the tests pass?

**Comment by dudicoco** [comment]
@jumanjiman i'm unable to access circle ci. Can you please specify what is failing?

**Comment by dudicoco** [comment]
@jumanjiman it seems like you are not available anymore. Is this repository unmaintained? Should I fork it instead?
Thanks

**Comment by TTRh** [comment]
interested in this one, any news ?

**Comment by dudicoco** [comment]
@jumanjiman can we please merge this PR?

**Comment by jumanjiman** [comment]
@dudicoco @TTRh 

tyvm! i'll push a new tag in a few minutes

**Comment by jumanjiman** [comment]
> i'll push a new tag in a few minutes

done: tag [`0.2.2`](https://github.com/jumanjihouse/pre-commit-hook-yamlfmt/releases/tag/0.2.2)

**Pull request merged**
