### PR TITLE
add implicit_start flag

### PR DESCRIPTION
**Pull request by dudicoco**
replaces the explicit_start flag (which basically does nothing) with implicit_start

### CODE REVIEW

**Comment by dudicoco** [comment]
@jumanjiman

**Comment by jumanjiman** [comment]
@dudicoco 

merged!

To me the usage of `implicit_start` reads like a double-negative in the code (a bit confusing), but it makes sense the way you wrote it.

Thanks  again!

**Comment by jumanjiman** [comment]
i also tagged it as 0.1.0

**Comment by dudicoco** [comment]
Thanks @jumanjiman!

**Pull request merged**
